# Generated by Django 5.0.7 on 2024-08-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='IMAGE',
            new_name='image',
        ),
    ]
