# Generated by Django 5.0.7 on 2024-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_overtime_hours_employee_overtime_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cellphone',
            field=models.TextField(default=528444192507, max_length=15),
            preserve_default=False,
        ),
    ]
