# Generated by Django 5.0.7 on 2024-08-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellphone',
            field=models.CharField(max_length=15),
        ),
    ]
