# Generated by Django 5.0.7 on 2024-08-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visibility',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
