# Generated by Django 5.0.7 on 2025-06-25 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0010_alter_drawing_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('out', 'To Client'), ('in', 'From Supplier')], default='out', help_text='‘out’ = sent to client; ‘in’ = received from supplier', max_length=3)),
                ('number', models.CharField(max_length=50)),
                ('date_issued', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotes', to='reportes.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='reportes.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_quotes', to='billing.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('equipment', 'Equipment'), ('overhead', 'Overhead')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='For labor/equipment: headcount; for materials: units', max_digits=8)),
                ('days', models.PositiveIntegerField(default=1, help_text='Number of days (ignored for materials/overhead)')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Daily rate for labor/equipment, per-unit cost for materials', max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='billing.supplier')),
            ],
        ),
    ]
