# Generated by Django 5.0.7 on 2025-06-25 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_type',
            field=models.CharField(choices=[('out', 'To Client'), ('in', 'From Supplier')], default='out', max_length=3),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='days',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tax ID'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, verbose_name='PO Number')),
                ('date_issued', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quotation', models.ForeignKey(limit_choices_to={'quote_type': 'in'}, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='billing.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('days', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.purchaseorder')),
            ],
        ),
    ]
