# Generated by Django 5.0.7 on 2025-06-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_quotationitem_quantity_quotationitem_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='coin',
            field=models.CharField(choices=[('USD', 'USD'), ('MXN', 'MXN')], default='MXN', max_length=3),
        ),
    ]
