# Generated by Django 5.0.7 on 2025-06-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_quotation_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor'), ('material', 'Material'), ('equipment', 'Equipment'), ('overhead', 'Overhead')], max_length=10),
        ),
    ]
