# Generated by Django 5.0.7 on 2025-06-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_quotationitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-date_issued']},
        ),
    ]
