# Generated by Django 5.0.7 on 2025-07-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_quotation_options'),
        ('reportes', '0011_project_notify_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='notify_contacts',
            field=models.ManyToManyField(blank=True, related_name='quotations', to='reportes.contact'),
        ),
    ]
