# Generated by Django 5.0.7 on 2025-07-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_quotation_notify_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
