# Generated by Django 5.0.7 on 2025-07-01 22:13

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_make_access_token_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='access_token',
            field=models.CharField(default=billing.models.generate_token, max_length=32, unique=True),
        ),
    ]
