# Generated by Django 5.0.7 on 2024-07-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
