# Generated by Django 5.0.7 on 2024-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_alter_post_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='static/landing/img/uploaded/'),
        ),
    ]
