# Generated by Django 5.0.7 on 2024-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_post_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
