# Generated by Django 5.0.7 on 2024-08-07 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_alter_post_attached'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
