# Generated by Django 5.0.7 on 2024-08-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.IntegerField(default=1),
        ),
    ]
