# Generated by Django 5.0.7 on 2024-08-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0007_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_view_blog', 'Can view blog')]},
        ),
    ]
