# Generated by Django 5.0.7 on 2025-06-12 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='client',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='equipmententry',
            name='report',
        ),
        migrations.RemoveField(
            model_name='manpowerentry',
            name='report',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='report',
            new_name='daily_report',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='daily_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='city_code',
            field=models.CharField(default=2500, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='humidity_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, default=444, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location_city',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reportes.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('hours_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='reportes.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manpower', to='reportes.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('temp_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('condition', models.CharField(max_length=100)),
                ('wind_kmh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity_pct', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'unique_together': {('city', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='ActivityEntry',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='EquipmentEntry',
        ),
        migrations.DeleteModel(
            name='ManpowerEntry',
        ),
    ]
