# Generated by Django 5.0.7 on 2025-06-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_client_alter_project_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='city_code',
        ),
    ]
