# Generated by Django 5.0.7 on 2025-06-13 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_remove_project_city_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
