# Generated by Django 5.0.7 on 2025-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='title',
        ),
        migrations.AddField(
            model_name='drawing',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.FileField(upload_to='project_drawings/'),
        ),
    ]
