# Generated by Django 5.0.7 on 2025-06-25 04:35

import reportes.models.data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_remove_drawing_title_drawing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.FileField(storage=reportes.models.data.AsciiFileSystemStorage(), upload_to='project_drawings/'),
        ),
    ]
