# Generated by Django 5.0.7 on 2025-07-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_alter_drawing_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notify_contacts',
            field=models.ManyToManyField(blank=True, related_name='notified_projects', to='reportes.contact'),
        ),
    ]
