# Generated by Django 5.0.7 on 2025-03-13 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Customer', max_length=200, verbose_name='Customer Name / Nombre del Cliente')),
                ('manager', models.CharField(default='Default Manager', max_length=100, verbose_name='Manager Name / Nombre del Gerente')),
                ('address', models.CharField(default='Default Address', max_length=255, verbose_name='Address / Dirección')),
                ('contact_email', models.EmailField(default='default@example.com', max_length=100, verbose_name='Contact Email / Correo Electrónico de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At / Actualizado En')),
            ],
        ),
        migrations.CreateModel(
            name='Contact2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Generico', max_length=50, verbose_name='Nombre / Name')),
                ('email', models.EmailField(default='default@example.com', max_length=50, verbose_name='Correo Electrónico / Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number / Número de Teléfono')),
                ('position', models.CharField(max_length=100, verbose_name='Position / Posición')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At / Actualizado En')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_profile', to=settings.AUTH_USER_MODEL, verbose_name='System User / Usuario del Sistema')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cotizaciones.customer', verbose_name='Customer / Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Default Project', max_length=200, verbose_name='Project Name / Nombre del Proyecto')),
                ('quotation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Quotation Date / Fecha de Cotización')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date / Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date / Fecha de Finalización')),
                ('project_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Project Cost / Costo del Proyecto')),
                ('currency', models.CharField(default='MXN', max_length=10, verbose_name='Currency / Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Exchange Rate / Tipo de Cambio')),
                ('payment_terms', models.CharField(default='30%', max_length=100, verbose_name='Payment Terms / Términos de Pago')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='Validity Date / Fecha de Validez')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At / Actualizado En')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='cotizaciones.contact2')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='cotizaciones.customer', verbose_name='Customer / Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(default='Default Material', max_length=100, verbose_name='Material Name / Nombre del Material')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specification / Especificación')),
                ('unit', models.CharField(default='pcs', max_length=50, verbose_name='Unit / Unidad')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Quantity / Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Cost / Costo Unitario')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At / Actualizado En')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='cotizaciones.quotation', verbose_name='Quotation / Cotización')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='Default Labor', max_length=200, verbose_name='Labor Item / Tarea Laboral')),
                ('worker_qty', models.PositiveIntegerField(default=1, verbose_name='Worker Quantity / Cantidad de Trabajadores')),
                ('work_days', models.PositiveIntegerField(default=1, verbose_name='Work Days / Días de Trabajo')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Price / Precio Unitario')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At / Actualizado En')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='cotizaciones.quotation', verbose_name='Quotation / Cotización')),
            ],
        ),
        migrations.CreateModel(
            name='IndirectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Default Indirect Cost', max_length=200, verbose_name='Cost Description / Descripción del Costo')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount / Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At / Actualizado En')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indirect_costs', to='cotizaciones.quotation', verbose_name='Quotation / Cotización')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Default Equipment', max_length=200, verbose_name='Equipment Description / Descripción del Equipo')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Quantity / Cantidad')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='Days / Días')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Unit Price / Precio Unitario')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At / Creado En')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At / Actualizado En')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='cotizaciones.quotation', verbose_name='Quotation / Cotización')),
            ],
        ),
    ]
