# Generated by Django 5.0.7 on 2025-03-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='contact',
        ),
    ]
