# Generated by Django 5.0.7 on 2024-09-23 04:29

import django.db.models.deletion
import facturador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=facturador.models.today)),
                ('average_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateTimeField()),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(max_length=10)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('tipo_de_comprobante', models.CharField(max_length=50)),
                ('tipo_cambio', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('concepto_descripcion', models.TextField(blank=True, null=True)),
                ('receptor_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('receptor_rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('traslado_importe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emisor_nombre', models.CharField(max_length=255)),
                ('emisor_rfc', models.CharField(max_length=255)),
                ('e_s', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('tax_type', models.CharField(max_length=100)),
                ('base', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('withholding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_production_ready', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('base', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('tax_type', models.CharField(default='IVA', max_length=50)),
                ('factor', models.CharField(choices=[('Tasa', 'Tasa'), ('Cuota', 'Cuota'), ('Exento', 'Exento')], default='Tasa', max_length=10)),
                ('withholding', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BankRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('exchange_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rates', to='facturador.exchangerate2')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livemode', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=500)),
                ('product_key', models.CharField(max_length=20)),
                ('material', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('machinery', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('tax_included', models.BooleanField(default=True, null=True)),
                ('taxability', models.CharField(choices=[('01', 'No objeto de impuesto'), ('02', 'Sí objeto de impuesto'), ('03', 'Sí objeto de impuesto, pero no obligado a desglose'), ('04', 'Sí objeto de impuesto, y no causa impuesto'), ('05', 'Sí objeto de impuesto, IVA crédito PODEBI')], default='01', max_length=2)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('local_taxes', models.ManyToManyField(blank=True, related_name='products', to='facturador.localtax')),
                ('taxes', models.ManyToManyField(blank=True, related_name='products', to='facturador.tax')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='facturador.unit')),
            ],
        ),
    ]
