# Generated by Django 5.0.7 on 2024-09-23 04:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
