# Generated by Django 5.0.7 on 2024-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0002_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(max_length=10)),
                ('usd_to_mxn_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
