# Generated by Django 5.0.7 on 2024-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0003_exchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_mxn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_mxn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='iva_mxn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
