# Generated by Django 5.0.7 on 2024-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0004_invoice_descuento_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancelacion_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
