# Generated by Django 5.0.7 on 2024-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0005_invoice_cancelacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='cancelacion_fecha',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
