# Generated by Django 5.0.7 on 2024-10-01 23:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturador', '0006_alter_invoice_cancelacion_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
